### ISSUE TITLE
Bug de rajoute d’items 

### ISSUE THREAD

**Issue by Willtom999** [HiroshimaMC/CustomThings#3]
![25D0EC13-8516-44F3-86FA-08FE6BBA8383](https://user-images.githubusercontent.com/83521998/133769473-280ea164-4cff-45a7-b76a-b6a1ae6a2b86.png)
![90BE2CBA-97A3-408D-A7C6-D0ED201BB0E0](https://user-images.githubusercontent.com/83521998/133769477-ae416c12-ad1f-417f-b4da-34830e39a498.png)
![450E3508-0164-4506-9A46-191C8EC50476](https://user-images.githubusercontent.com/83521998/133769479-916117bf-8f54-41fa-855c-71e74570598e.png)
![D19D25B4-D6E5-40AB-BE19-52E60BE52D9E](https://user-images.githubusercontent.com/83521998/133769480-1c02ac19-2634-4e27-acd3-6b02714f802f.png)

**Comment by Nya-Enzo** [comment]
tu as quelle version de pocketmine ? La 4.0 ou la 3.22.5 ?

**Comment by RomainSav** [comment]
More details please. We don't see anything on your screenshots.
_(Like your configuration)_

**Comment by Willtom999** [comment]
la plus recente

**Comment by Willtom999** [comment]
stable pm3 # @Nya-Enzo

**Comment by Steellgold** [comment]
You have given yourself a non-existent item, delete your player file, or create the item with the id (1999) in the configuration

**Comment by Steellgold** [comment]
You have given yourself a non-existent item, delete your player file, or create the item with the id (1999) in the configuration

**Comment by Willtom999** [comment]
![4B5E9453-9CF1-4BE0-B917-F7FC79AD0466](https://user-images.githubusercontent.com/
![5E650236-F5EB-4BF0-8A8E-5F88C15376D9](https://user-images.githubusercontent.com/83521998/133895719-369b9077-bca8-411e-a13a-ba29636ad1b2.png)
 @Steellgold 83521998/133895715-e67b327a-fb9f-4712-b769-70834b655f79.png)
![8B317166-9E59-491A-9599-BB61346308A4](https://user-images.githubusercontent.com/83521998/133895716-889b7454-791e-49fa-acba-d5715241a603.png)

**Comment by Willtom999** [comment]
![B4AB3653-BC87-4E55-881E-33D6D701398C](https://user-images.githubusercontent.com/83521998/133895741-4fb060cb-c3b7-4924-a83a-ef5183c3ba17.png)

**Comment by Willtom999** [comment]
@RomainSav

**Comment by Willtom999** [comment]
Sais pas possible de fair beaucoup plus d’item genre?

**Comment by Willtom999** [comment]
Genre sa va être régler?

**Comment by Nya-Enzo** [comment]
Faut download la derniere version sur le github, cest fix. Mais tous les items vont dans le items.json pas dans des fichiers séparés !

**Comment by Willtom999** [comment]
ok
